trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'azure container registry'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/*Dockerfile'
        buildContext: 'Dockerfile'
        tags: '$(tag)'