trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'azure container registry'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        buildContext: '**/Dockerfile'
        tags: '$(tag)'
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1 (5a0eee50-4814-4a84-babe-068c6bee0201)'
        azureContainerRegistry: '{"loginServer":"pythonapplication.azurecr.io", "id" : "/subscriptions/5a0eee50-4814-4a84-babe-068c6bee0201/resourceGroups/svcloudtech/providers/Microsoft.ContainerRegistry/registries/pythonapplication"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
    